# Generated by Django 5.2.8 on 2025-12-26 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WishList",
        ),
    ]
