# Generated by Django 5.2.8 on 2025-12-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_invoice_file_order_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card_last_4",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Credit Card", max_length=50),
        ),
    ]
