# Generated by Django 5.2.7 on 2025-12-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_card_last_4_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_log",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
