# Generated by Django 5.2.7 on 2026-01-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_products_pr_is_acti_ca4d9a_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="version",
            field=models.PositiveIntegerField(
                default=0, help_text="Version for optimistic locking"
            ),
        ),
    ]
